/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var u=Object.getOwnPropertyNames;var S=Object.prototype.hasOwnProperty;var w=(s,e)=>{for(var t in e)o(s,t,{get:e[t],enumerable:!0})},b=(s,e,t,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of u(e))!S.call(s,i)&&i!==t&&o(s,i,{get:()=>e[i],enumerable:!(n=h(e,i))||n.enumerable});return s};var m=s=>b(o({},"__esModule",{value:!0}),s);var P={};w(P,{default:()=>l});module.exports=m(P);var g=require("obsidian"),C={respectHeadings:!0},l=class extends g.Plugin{async onload(){await this.loadSettings(),this.addCommand({id:"add-section",name:"Add Section",editorCallback:t=>{if(!this.settings.respectHeadings){t.setCursor(0,0);let a=`

---

`;t.replaceRange(a,{line:0,ch:0});return}let n=t.getCursor(),d=t.getValue().split(`
`),c=n.line;for(let a=n.line-1;a>=0;a--)if(d[a].match(/^#{1,6}\s/)){c=a+1;break}let p=`


---
`;t.replaceRange(p,{line:c,ch:0}),t.setCursor(c+1,0)}}),this.addSettingTab(new r(this.app,this))}async loadSettings(){this.settings=Object.assign({},C,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}},r=class extends g.PluginSettingTab{constructor(t,n){super(t,n);this.plugin=n}display(){let{containerEl:t}=this;t.empty(),new g.Setting(t).setName("Respect Headings").setDesc("When enabled, new sections will be inserted above the nearest heading").addToggle(n=>n.setValue(this.plugin.settings.respectHeadings).onChange(async i=>{this.plugin.settings.respectHeadings=i,await this.plugin.saveSettings()}))}};
