/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoticeLoggerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enableLogging: true,
  prefix: "",
  timestamp: "YYYY-MM-DD HH:mm:ss"
};
var NoticeLoggerPlugin = class extends import_obsidian.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.observers = [];
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "enable-notice-logging",
      name: "Enable notice logging",
      callback: async () => {
        this.enableLogging();
      }
    });
    this.addCommand({
      id: "disable-notice-logging",
      name: "Disable notice logging",
      callback: async () => {
        this.disableLogging();
      }
    });
    const startObserving = (domNode, classToLookFor, settings) => {
      const observer = new MutationObserver((mutations) => {
        mutations.forEach(function(mutation) {
          const elementAdded = Array.from(mutation.addedNodes).some(
            (element) => {
              if (element.classList) {
                if (element.classList.contains(classToLookFor)) {
                  return true;
                }
              } else {
                return false;
              }
            }
          );
          if (elementAdded) {
            mutation.addedNodes.forEach((notice) => {
              if (settings.enableLogging) {
                let noticeLogItem = "";
                if (settings.prefix !== "") {
                  noticeLogItem += settings.prefix + " ";
                }
                if (settings.timestamp !== "") {
                  noticeLogItem += "[" + (0, import_obsidian.moment)().format(settings.timestamp) + "] ";
                }
                noticeLogItem += notice.textContent;
                console.log(noticeLogItem);
              }
            });
          }
        });
      });
      observer.observe(domNode, {
        childList: true,
        attributes: true,
        characterData: true,
        subtree: true
      });
      this.observers.push(observer);
      return observer;
    };
    const parent = document.querySelector("body");
    startObserving(parent, "notice", this.settings);
    this.addSettingTab(new NoticeLoggerSettingTab(this.app, this));
    console.log("Notice logger plugin loaded");
  }
  onunload() {
    this.observers.forEach((obs) => {
      obs.disconnect();
    });
    console.log("Notice logger plugin unloaded");
  }
  async enableLogging() {
    this.settings.enableLogging = true;
    await this.saveSettings();
    new import_obsidian.Notice("Notice logging enabled");
  }
  async disableLogging() {
    this.settings.enableLogging = false;
    await this.saveSettings();
    new import_obsidian.Notice("Notice logging disabled");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var NoticeLoggerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable logging").setDesc("").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableLogging).onChange(async (newValue) => {
        this.plugin.settings.enableLogging = newValue;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Prefix").setDesc("Prepend console log lines with this string. Leave blank to disable. (e.g. \u2705)").addText((text) => text.setPlaceholder("Enter your prefix").setValue(this.plugin.settings.prefix).onChange(async (value) => {
      this.plugin.settings.prefix = value;
      await this.plugin.saveSettings();
    }));
    let descMomentFormat = document.createDocumentFragment();
    descMomentFormat.append(
      "Prepend console log lines with [timestamp]. Leave blank to disable.",
      descMomentFormat.createEl("br"),
      "Learn about available formatting tokens in the ",
      descMomentFormat.createEl("a", {
        href: "https://momentjs.com/docs/#/displaying/format/",
        text: "moment.js documentation",
        attr: { "aria-label": "https://momentjs.com/docs/#/displaying/format/", "data-tooltip-position": "top", "tabindex": "0" }
      }),
      "."
    );
    new import_obsidian.Setting(containerEl).setName("Timestamp").setDesc(descMomentFormat).addText((text) => text.setPlaceholder("YYYY-MM-DD HH:mm:ss").setValue(this.plugin.settings.timestamp).onChange(async (value) => {
      this.plugin.settings.timestamp = value;
      await this.plugin.saveSettings();
    }));
  }
};

/* nosourcemap */